version: "3"
services:
  filelist:
    image: ywgx/filelist
    depends_on:
      - redis
      - mongo
    restart: always
    volumes:
      - /opt/data/filelist:/opt/files
    links:
      - redis
      - mongo
    ports:
      - 80:10000
    environment:
      - TZ=Asia/Shanghai
    container_name: filelist
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - /opt/2/redis:/data
    ports:
      - 127.0.0.1:6379:6379
    environment:
      - TZ=Asia/Shanghai
    container_name: redis
  mongo:
    image: mongo
    restart: always
    volumes:
      - /opt/2/mongo/db:/data/db
      - /opt/2/mongo/configdb:/data/configdb
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - TZ=Asia/Shanghai
    container_name: mongo
